--  Load configuration options up front
ScriptHost:LoadScript("scripts/settings.lua")
ScriptHost:LoadScript("scripts/logic.lua")

Tracker:AddMaps("maps/maps.json")
Tracker:AddItems("items/common.json")
Tracker:AddLocations("locations/Caves-FluffyFields.json")
Tracker:AddLocations("locations/Caves-FancyRuins.json")
Tracker:AddLocations("locations/Caves-FrozenCourt.json")
Tracker:AddLocations("locations/Caves-StarWoods.json")
Tracker:AddLocations("locations/Caves-SweetwaterCoast.json")
Tracker:AddLocations("locations/Caves-SlipperySlope.json")
Tracker:AddLocations("locations/Caves-PepperpainPrairie.json")
Tracker:AddLocations("locations/Caves-LonelyRoad.json")
Tracker:AddLocations("locations/PillowFort.json")
Tracker:AddLocations("locations/SandCastle.json")
Tracker:AddLocations("locations/ArtExhibit.json")
Tracker:AddLocations("locations/TrashCave.json")
Tracker:AddLocations("locations/FloodedBasement.json")
Tracker:AddLocations("locations/PotassiumMine.json")
Tracker:AddLocations("locations/BoilingGrave.json")
Tracker:AddLocations("locations/GrandLibrary.json")
Tracker:AddLocations("locations/SunkenLabyrinth.json")
Tracker:AddLocations("locations/MachineFortress.json")
Tracker:AddLocations("locations/DarkHypostyle.json")
Tracker:AddLocations("locations/TombOfSimulacrum.json")
Tracker:AddLocations("locations/PortalWorlds.json")
Tracker:AddLocations("locations/DreamWorld.json")
Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/tracker.json")
-- Tracker:AddLayouts("layouts/tracker_broadcast.json")
